name: Build Plugin and Draft Release

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "src/**"

permissions:
  contents: write

jobs:
  checktag:
    name: Check for existing version tag
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.set_output.outputs.version }}
      pluginname: ${{ steps.set_output.outputs.pluginname }}

    steps:
      - uses: actions/checkout@v5

      - name: Get version
        run: |
            echo "PackageVersion=$(cat package.json | jq --raw-output '.version')" >> $GITHUB_ENV

      - name: Get script name
        run: |
            echo "PluginName=$(cat package.json | jq --raw-output '.scriptOutputName')" >> $GITHUB_ENV

      - name: Check for corresponding git tag
        id: tag_check
        uses: mukunku/tag-exists-action@v1.6.0
        with:
          tag: "$PackageVersion"

      - name: Fail on existing tag
        if: ${{ steps.tag_check.outputs.exists == 'true' }}
        run: exit 1

      - name: Set Output
        id: set_output
        run: |
          echo "version=$PackageVersion" >> $GITHUB_OUTPUT &&
          echo "pluginname=$PluginName" >> $GITHUB_OUTPUT

  build:
    name: Build plugin
    needs: checktag
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: '22.19.0'
          
      - name: Install Project Dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.checktag.outputs.pluginname }} Release
          path: ./dist/${{ needs.checktag.outputs.pluginname }}.js

  release:
    name: Draft Release
    needs: [checktag, build]
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v5
        with:
          name: ${{ needs.checktag.outputs.pluginname }} Release
          path: ./artifacts/

      - name: Draft Release
        id: draft
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.checktag.outputs.version }}
          name: ${{ needs.checktag.outputs.version }}
          body: "## Release Notes\n\n- "
          draft: true
          prerelease: false
          files: |
            ./artifacts/${{ needs.checktag.outputs.pluginname }}.js